version: '3.8'

networks:
  wordpress-nwk: {}

services:
  mysql:
    container_name: mysqldb
    env_file: ./.env
    image: mysql
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    networks:
      - wordpress-nwk 

  app:
    image: mikuxi/api-test
    env_file: ./.env
    ports:
      - $NODE_DOCKER_PORT
    environment:
      PORT: 80
      DB_HOST: mysql
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    networks:
      - wordpress-nwk 

